valor = input('Escreva: ')
tipo = type(valor)
a = valor.isalpha()
um = valor.isnumeric()
a1 = valor.isalnum()
f = valor.isdecimal()
Ma = valor.isupper()
Mi = valor.islower()
space = valor.isspace()
print('Qual o tipo primitivo de {}: {}'.format(valor, tipo))
print('É alfabético? {}'.format(a))
print('É numérico? {}'.format(um))
print('É alfanumérico? {}'.format(a1))
print('Tem maiusculas? {}'.format(Ma))
print('Tem minusculas? {}'.format(Mi))
print('Só tem espaços? {}'.format(space))
print('Está capitalizado?', valor.istitle())